steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/rackspace/austinjones-ops-f71d:$SHORT_SHA',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'push',
        'gcr.io/rackspace/austinjones-ops-f71d:$SHORT_SHA'
      ]

